[package]
description = "Cartesi Verification Game Test (Cache)"
homepage = "https://cartesi.io"
name = "arbitration_test"
version = "0.1.0"
authors = ["Cartesi Team"]

[dependencies]
protobuf = "~2"
log = "0.4"
env_logger = "0.6.0"
ethereum-types = "0.4"
ethabi = "6.1.0"
serde_json = "1.0"
serde = "1.0.0"
serde_derive = "1.0.0"
web3 = { git = "https://github.com/cartesi/rust-web3", branch = "v0.6.0-implement-chain-id" }
ethcore = { git = "https://github.com/cartesi/parity-ethereum", branch = "stable-fixed" }